language: ruby
bundler_args: --without development
script: "bundle exec rspec spec"
env:
  - CI=true
rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2.1
  - jruby
cache: bundler
sudo: false
matrix:
  allow_failures:
    - rbx-2

